# Generated by Django 3.1.2 on 2020-11-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='logo',
            field=models.ImageField(blank=True, upload_to='healthlogo/'),
        ),
    ]
