# Generated by Django 3.1.2 on 2020-11-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_remove_business_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
