# Generated by Django 3.1.2 on 2020-11-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20201102_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
