# Generated by Django 3.1.2 on 2020-11-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_business_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorities',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='health',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
