# Generated by Django 3.1.2 on 2020-11-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0009_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
